const width: number = 3;
const height: number = 4;
const area: number = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill: number = 100;
const payment: number = 150;
const change: number = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes: number = 86;
const midterm: number = 93;
const final: number = 98;
const grade: number = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName: string = 'Eduardo ';
const lastName: string = 'Gallegos';
const fullName: string = firstName + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const ph: number = 8;
const isAcidic: boolean = ph < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount: number = 241;
const isSparta: boolean = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto: string = 'Eduardo Gallegos ' + 'is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
