'use strict';
const width = 3;
const height = 4;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 100;
const payment = 150;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 86;
const midterm = 93;
const final = 98;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Eduardo ';
const lastName = 'Gallegos';
const fullName = firstName + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const ph = 8;
const isAcidic = ph < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 241;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto = 'Eduardo Gallegos ' + 'is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
